/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the LiveValidationError class.
 * @constructor
 * Describes the error occurred while performing validation on live
 * request/response.
 *
 * @member {string} code The unique error code describing an error.
 *
 * @member {string} message The error message providing meaningful information.
 *
 */
class LiveValidationError {
  constructor() {
  }

  /**
   * Defines the metadata of LiveValidationError
   *
   * @returns {object} metadata of LiveValidationError
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'LiveValidationError',
      type: {
        name: 'Composite',
        className: 'LiveValidationError',
        modelProperties: {
          code: {
            required: true,
            serializedName: 'code',
            type: {
              name: 'String'
            }
          },
          message: {
            required: true,
            serializedName: 'message',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = LiveValidationError;
